### ISSUE TITLE
Add GitHub Repository Link in the Interface

### ISSUE THREAD

**Issue by yarons** [ivrit-ai/crowd-transcribe#2]
**Is your feature request related to a problem? Please describe.**
I need to search Google to get to this repo.

**Describe the solution you'd like**
GitHub link in the UI.

**Describe alternatives you've considered**
Searching Google.

**Additional context**
Sorry for nagging.

**Comment by yoadsn** [comment]
@yanirmr I assume we mean here the GH link for the dataset/training repo - not the crowd-transcribe server.
Right?
We can just link to the Ivrit.ai ORG on GH to capture both.
Wdyt?

**Comment by yarons** [comment]
It will be a more straightforward approach to redirect to the thing the user sees on screen, several links are also possible.

**Comment by yoadsn** [comment]
I ended up linking to the Org for now - This can be changed easily if it will be decided to be a mistake.
I think orientation of a user to "where code is" is achieved - without making assumption about which code is of interest. I know Yair plans to create more repos under this org - this will make listing all GH links cumbersome.
PR #19 Also adds the HF org link.

**Comment by yairl** [comment]
Resolved by PR #19.
